/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ConnectDevice`; params?: Router.UnknownInputParams; } | { pathname: `/CreateChalk`; params?: Router.UnknownInputParams; } | { pathname: `/JoinChalk`; params?: Router.UnknownInputParams; } | { pathname: `/JumpData`; params?: Router.UnknownInputParams; } | { pathname: `/LetGo`; params?: Router.UnknownInputParams; } | { pathname: `/Map`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/paxdata` | `/paxdata`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ConnectDevice`; params?: Router.UnknownOutputParams; } | { pathname: `/CreateChalk`; params?: Router.UnknownOutputParams; } | { pathname: `/JoinChalk`; params?: Router.UnknownOutputParams; } | { pathname: `/JumpData`; params?: Router.UnknownOutputParams; } | { pathname: `/LetGo`; params?: Router.UnknownOutputParams; } | { pathname: `/Map`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/paxdata` | `/paxdata`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/ConnectDevice${`?${string}` | `#${string}` | ''}` | `/CreateChalk${`?${string}` | `#${string}` | ''}` | `/JoinChalk${`?${string}` | `#${string}` | ''}` | `/JumpData${`?${string}` | `#${string}` | ''}` | `/LetGo${`?${string}` | `#${string}` | ''}` | `/Map${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/paxdata${`?${string}` | `#${string}` | ''}` | `/paxdata${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ConnectDevice`; params?: Router.UnknownInputParams; } | { pathname: `/CreateChalk`; params?: Router.UnknownInputParams; } | { pathname: `/JoinChalk`; params?: Router.UnknownInputParams; } | { pathname: `/JumpData`; params?: Router.UnknownInputParams; } | { pathname: `/LetGo`; params?: Router.UnknownInputParams; } | { pathname: `/Map`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/paxdata` | `/paxdata`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
